//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallHospitalDataBaseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatments
    {
        public int treatment_id { get; set; }
        public string treat_name { get; set; }
        public int diagnosis_id { get; set; }
        public System.DateTime treatment_date { get; set; }
        public string treat_description { get; set; }
    
        public virtual diagnosis diagnosis { get; set; }
    }
}
