//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallHospitalDataBaseApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyHospitalDBEntities : DbContext
    {
        public MyHospitalDBEntities()
            : base("name=MyHospitalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<diagnosis> diagnosis { get; set; }
        public virtual DbSet<doctors> doctors { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<treatments> treatments { get; set; }
        public virtual DbSet<visits> visits { get; set; }
    }
}
